version: 0.0
os: linux
files:
  - source: /build/libs
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
