version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Installing source dependencies
      - chmod +x gradlew
      - ./gradlew dependencies
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - appspec.yml
    - build/libs/**/*.jar
    - scripts/*.sh
